"""empty message

Revision ID: 0dc554ed9ea2
Revises: 9c1a269f157b
Create Date: 2023-03-08 19:16:21.200111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc554ed9ea2'
down_revision = '9c1a269f157b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(precision=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.Column('user_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.ForeignKeyConstraint(['user_ticket_id'], ['user_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.Column('user_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.ForeignKeyConstraint(['user_ticket_id'], ['user_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('ticket')
    op.drop_table('payments')
    op.drop_table('user_ticket')
    # ### end Alembic commands ###
