"""empty message

Revision ID: 339bc44e81d9
Revises: 70ca77d3e1d2
Create Date: 2023-03-09 11:17:40.235154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339bc44e81d9'
down_revision = '70ca77d3e1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=False),
    sa.Column('number_of_tickets', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(precision=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.Column('user_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.ForeignKeyConstraint(['user_ticket_id'], ['user_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payments')
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('talonario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_tickets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.REAL(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], name='payments_talonario_id_fkey'),
    sa.ForeignKeyConstraint(['user_ticket_id'], ['user_ticket.id'], name='payments_user_ticket_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###
