"""empty message

Revision ID: 70ca77d3e1d2
Revises: c74b15745d7b
Create Date: 2023-03-08 20:19:44.503734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ca77d3e1d2'
down_revision = 'c74b15745d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('number')

    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
