"""empty message

Revision ID: 9c1a269f157b
Revises: d15b39c2e2a6
Create Date: 2023-03-08 14:22:22.119357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1a269f157b'
down_revision = 'd15b39c2e2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talonario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prize', sa.String(length=200), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=10), nullable=False),
    sa.Column('img_prize', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talonario')
    # ### end Alembic commands ###
