"""empty message

Revision ID: a2b7de5023b9
Revises: 339bc44e81d9
Create Date: 2023-03-09 19:17:14.727061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b7de5023b9'
down_revision = '339bc44e81d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url_prize', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('img_cloud_id', sa.String(length=120), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['img_cloud_id'])
        batch_op.drop_column('payment_method')
        batch_op.drop_column('img_prize')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('img_prize', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('img_cloud_id')
        batch_op.drop_column('img_url_prize')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
