"""empty message

Revision ID: ebb47da3deec
Revises: 0b6c44138060
Create Date: 2023-04-18 20:49:50.392604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb47da3deec'
down_revision = '0b6c44138060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
        batch_op.drop_constraint('payment_email_key', type_='unique')
        batch_op.drop_constraint('payment_phone_key', type_='unique')

    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talonario', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_unique_constraint('payment_phone_key', ['phone'])
        batch_op.create_unique_constraint('payment_email_key', ['email'])
        batch_op.alter_column('total',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
