"""empty message

Revision ID: f722698b96e2
Revises: 
Create Date: 2023-04-14 12:18:06.022231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f722698b96e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'raffler', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('talonario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prize', sa.String(length=200), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=10), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('img_url_prize', sa.String(length=200), nullable=False),
    sa.Column('img_cloud_id', sa.String(length=120), nullable=False),
    sa.Column('talonario_id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_cloud_id'),
    sa.UniqueConstraint('talonario_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=False),
    sa.Column('number_of_tickets', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(precision=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('payment')
    op.drop_table('talonario')
    op.drop_table('user')
    # ### end Alembic commands ###
